### ISSUE TITLE
Странные показания потолка ограничений

### ISSUE THREAD

**Issue by iprst** [terratensor/common-library-app#10]
- Запрос [ленский расстрел](https://svodd.ru/VIw4ubLh) показывает ограничение в 10 тысяч, но по факту там всего три страницы, четвёртая пустая.
- Запрос [ленские события](https://svodd.ru/OaMkpnPx) также показывает потолок 10 тысяч, но с третьей страницы — пустота.
- Запрос [ленское золото](https://svodd.ru/Xrr86cS5) тоже упирается в 10 тысяч, но как и предыдущий запрос пуст с третьей страницы. 
- Запрос [ленский](https://svodd.ru/OW96y2i7) вновь показывает ограничение, однако в выдаче результаты есть лишь до 28 страницы, далее пусто. 
- Запрос [расстрел](https://svodd.ru/lXaV2mOd) показывает ограничение честно — последняя страница выдачи содержит результаты. 
- Запрос [золото](https://svodd.ru/nf9hGQL4) также имеет честное ограничение, последняя страница содержит информацию. 
- Запрос [события](https://svodd.ru/jfiDk032) снова встречает честный потолок и имеет данные на последней странице выдачи. 

Получается, что показываемый потолок относится только к одному слову из словосочетания, которое такой потолок в действительности встречает в одиночку, таким образом потолок никак не отображает реальную картину для словосочетания, во всяком случае в режиме поиска по умолчанию.

**Comment by audetv** [comment]
Исправил, обновлено на сервере

**Comment by iprst** [comment]
#11 исправляет данное поведение. Теперь работает как надо.
