### ISSUE TITLE
Тег description для главной страницы поиска по военно-исторической-библиотеке.

### ISSUE THREAD

**Issue by audetv** [terratensor/common-library-app#21]
> Поиск по военно-исторической-библиотеке.

Отлично.

> Можно ещё в тег description добавить короткое предложение, и этого будет достаточно, чтобы при в выдаче выглядело хорошо , можно только титл:

Значит, надо придумать описание из одного предложения.

_Originally posted by @iprst in https://github.com/terratensor/svodd/issues/215#issuecomment-1647577582_

**Comment by audetv** [comment]
Предлагаю взять из вашего объявления:

> Сделал [объявление](https://%D1%84%D0%BA%D1%82-%D0%B0%D0%BB%D1%82%D0%B0%D0%B9.%D1%80%D1%84/qa/question/view-3158#:~:text=10:42%2024.07.2023) об открытии поисковика по военно-исторической библиотеке.

Title:
Поиск по военно-исторической библиотеке

Dtscription:
В настоящий момент собрано 11 тысяч томов преимущественно русскоязычных авторов, в которых широко раскрыты большинство исторических событий — это документальная, научная, историческая литература, а также воспоминания, мемуары, дневники и письма, издававшиеся в форме собраний сочинений и художественной литературы.

**Comment by audetv** [comment]
Или: 
Цитаты из более 11 тысяч томов преимущественно русскоязычных авторов, в которых широко раскрыты большинство исторических событий — это документальная, научная, историческая литература, а также воспоминания, мемуары, дневники и письма, издававшиеся в форме собраний сочинений и художественной литературы.

**Comment by iprst** [comment]
Можно «более» убрать, и отправлять в печать: 

Цитаты из 11 тысяч томов преимущественно русскоязычных авторов, в которых широко раскрыты большинство исторических событий — это документальная, научная, историческая литература, а также воспоминания, мемуары, дневники и письма, издававшиеся в форме собраний сочинений и художественной литературы.
