### ISSUE TITLE
Поправить кнопку короткая ссылка 

### ISSUE THREAD

**Issue by audetv** [terratensor/common-library-app#24]
Планшет в вертикальном расположении, как книга. 
<details><summary>Details</summary>
<p>

![Screenshot_20230729_173958](https://github.com/terratensor/common-library-app/assets/10896447/2667c046-1171-488e-bb86-461fc3bd0c64)

</p>
</details>

**Comment by iprst** [comment]
Кнопка пострадала из-за названия «Поиск по военно-исторической библиотеке»?

**Comment by audetv** [comment]
Там 99% вопрос в том, что кнопка принимает всю высоту блока, в котором находится, надо это поведение будет подправить. И тогда хлебные крошки могут хоть на 3 строки размещаться, надо только выбрать где  размещать кнопку сверху блока, по центру или снизу. Причём такое соотношение экрана, происходит скорее всего только на планшетах. Ещё можно поставить` &nbsp`  неразрывный пробел перед звездой, чтобы уж если сломается кнопка, то по словам, `короткая` перенос `ссылка и звезда`, а не звезда отдельно снизу. Пометил, чтобы не забыть, исправлю.
