### ISSUE TITLE
Ошибка #2 при просмотре контекста

### ISSUE THREAD

**Issue by audetv** [terratensor/common-library-app#32]
Власов ★ https://svodd.ru/ySoyNCt5

Выявлено, что ошибка возникает у некоторых дублированных параграфов, по одному из параграфов контекст открывается, по другому вызывает ошибку.

Например. Ищем Ctrl+f поиском по странице: 
```
Кто такой Власов?
```
будет 5 результатов.

Контекст книги:  «Соколов Б.В. Оккупация. Правда и мифы» вызывает ошибку, остальные страницы открываются.

На той же странице ищем ctrl+f  
```
Но — увы! — воспоминания этих людей не сохранились… [21]
```
один из дублированных параграфов контекста книги «Коняев Н.М. Власов. Два лица генерала» вызывает ошибку

Данные лога сервера
```
 Undefined array key 0 in /app/vendor/manticoresoftware/manticoresearch-php/src/Manticoresearch/ResultSet.php:65
Stack trace:
#0 /app/vendor/manticoresoftware/manticoresearch-php/src/Manticoresearch/ResultSet.php(65): yii\base\ErrorHandler->handleError(2, 'Undefined array...', '/app/vendor/man...', 65)
#1 /app/src/repositories/ParagraphRepository.php(305): Manticoresearch\ResultSet->current()
#2 /app/src/services/NeighboringService.php(23): src\repositories\ParagraphRepository->findByParagraphUuid('ae16eb12-2f95-4...')
#3 /app/controllers/SiteController.php(106): src\services\NeighboringService->handle(Object(src\forms\QuoteForm))
#4 [internal function]: app\controllers\SiteController->actionQuote()
#5 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#6 /app/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#7 /app/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('quote', Array)
#8 /app/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('site/quote', Array)
#9 /app/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#10 /app/web/index.php(13): yii\base\Application->run()
#11 {main}
2023-08-19 15:57:41 [10.0.1.31][-][7636b39dc045334d6781fa991328b38e][info][application] $_GET = []
```

https://github.com/terratensor/common-library-app/blob/7a5bec218e3615cafc72460a39a855cc48412fd7/app/src/repositories/ParagraphRepository.php#L305

**Comment by iprst** [comment]
> Контекст книги: «Соколов Б.В. Оккупация. Правда и мифы» вызывает ошибку, остальные страницы открываются.

Если открыть xml исходного документа там будет следующая конструкция:

```xml
Вот что там говорилось: 
</w:t></w:r></w:p>
<w:p><w:pPr><w:spacing w:before="240" w:after="240" />
<w:ind w:left="600" w:right="600" /></w:pPr>
<w:r><w:t>
«Смерть презренному предателю!
</w:t></w:r></w:p>
<w:p><w:pPr><w:spacing w:before="240" w:after="240" />
<w:ind w:left="600" w:right="600" /></w:pPr>
<w:r><w:t>
Бывший советский генерал Власов 
```

Для справки, ворд эту конструкцию воспринимает вот так: 

![image](https://github.com/terratensor/common-library-app/assets/129882753/b37961b4-0618-466e-89ad-33a2a5cf913b)

> один из дублированных параграфов контекста книги «Коняев Н.М. Власов. Два лица генерала» вызывает ошибку

Идентичная картина со вторым файлом, там такая же конструкция с отступом

```xml
Михаилом Николаевичем Ворониным.
</w:t></w:r></w:p>
<w:p><w:pPr><w:spacing w:before="240" w:after="240" />
<w:ind w:left="600" w:right="600" /><w:outlineLvl w:val="1" />
<w:rPr><w:b w:val="1" /><w:sz w:val="36" /></w:rPr></w:pPr>
<w:r><w:rPr><w:b w:val="1" /><w:sz w:val="36" /></w:rPr>
<w:t>
«Мне, как и ему
```

Пока больше ничего в глаза не бросилось.

**Comment by audetv** [comment]
Ещё раз наткнулся на эту ошибку, в этот раз я уже проверил локально этот параграф. т.к. индекс выгружен с локальной машины на сервер, они совпадают. Так вот, эта ошибка не является следствием содержимого оригинального файла, оригинал контекста не причём.

Это что то с индексом, запись не находиться по uuid, и далее происходит обращение к несуществующему объекту и вылетает исключение. Причем запись с uuid есть в БД:
```
------------+--------------------------------------+---------+----------+--------+
| 1869764 | Курмачева М.Д. Города Урала и Поволжья в крестьянской войне 1773-1775 гг. 1991                                                    | <div>Известно, что в манифестах и указах Пугачева провозглашалось пожалование землей, в которой было заинтересовано в первую очёрѳдь крестьянство. Уже первый указ от 17 сентября 1773 г. яицким казакам содержал это важнейшее положение. Из наиболее ярких в этом отношении документов назовем манифест от 28 июля, объявленный в Саранске, и от</div><div>31 июля 1774 г , объявленный в Пензе. Однако ряд повстанческих воззваний не содержит этого важнейшего положения, в них говорится только об освобождении от податей и рекрутских наборов. При этом обнаруживается, что его отсутствие относится к тем из сохранившихся указов, которые были обращены непосредственно к жителям городов Алатыря, Саранска, Пензы. И только один именной указ от 12 июля был выдан государственному крестьянину слободы Белый Яр под Екатеринбургом, названному "сыном Отечества”, атаману Федоту Тихоновичу Кочневу. Что касается указов, объявленных в городах, то это - именной указ от 23 июля 1774 г. о производстве прапорщика Е.З.Сулдѳшѳва в полковники и о назначении его управителем г.Алатыря, именной указ от 28 июля о назначении прапорщика М.Шахмамѳтова управителем г.Саранска, именной указ от 3 августа о назначении секунд-майора Г.Г .Герасимова управителем г.Пензы, награждении его чином полковника и определении в товарищи к нему пензенского купца А.Я .Кознова.</div><div>Подавляющее большинство манифестов и указов неизменно объявляло об освобождении от подушных и "протчих денежных податей”, "отяго- щѳниѳв” рекрутских наборов и стремлении к ”благополучию” "благоцветущему состоянию”!?. Постоянным также было указание, в том числе и по отношению к горожанам, не причинять никому ”обид, налог и притѳснѳ- ниев”. В именном указе от 28 июля о назначении прапорщика М.Шахмаме- това управителем г.Саранска ему вменялось в обязанность защищать не только ”всего уезду обывателей всякаго звания и чина”, но и "обывателей” ”здешняго города”18.</div> | aff39c45-ec41-488e-b7d5-5edcac3bdc1c |    5620 |      214 |   1913 |
+---------+-------------------------------------------------------------------------------------------------------------------------------
``` 

Но по запросу ничего не находит.
```
select * from common_library where uuid='aff39c45-ec41-488e-b7d5-5edcac3bdc1c';
```

Странная история. попробую переиндексировать, как будет возможность, может быть при переключении типов произошел какой-то сбой.  Я уже не помню, но возможно колоночный режим хранения я включил позже и переиндексировал уже по существующему индексу. Возможно надо было все обнулить. Но это все не точно. 
Пока нет решения.

**Comment by iprst** [comment]
Очень странное поведение, но раз не ищется сам uuid, то видимо только индексировать. 
Интересно, как понять, сколько информации отсутствует из-за утери uuid?

**Comment by audetv** [comment]
> Интересно, как понять, сколько информации отсутствует из-за утери uuid?

uuid используется только для контекста, и нужен он чтобы по этому uuid отфильтровать параграф и получить его числовой id, возможно, что uuid я добавил позже, уже не помню. В поиске uuid не используется, это не индексируемая для поиска поле, только для фильтра. Обычным поиском match не фильтром этот параграф ищется. 

Предполагаю, что информация вся в индексе и ищется обычным поиском, т.к. в конце индексации индексер писал, сколько записей было проиндексировано и добавлено, и это точно совпадало с тем что было в БД, я на это обращал внимание. Но если уж так прямо заморочится, то можно написать программу, взять каждую текстовую запись из БД, например одно предложение и отправить в поиск, получить результат, если не найдено записать запрос в лог для проверки, если ок записать uuid записи в лог и потом как-то проанализировать. 

Для начала надо переиндексировать локально и посмотреть, что будет с этими параграфами, которые уже в ошибках зафиксированы.

**Comment by iprst** [comment]
> В поиске uuid не используется, это не индексируемая для поиска поле, только для фильтра. Обычным поиском match не фильтром этот параграф ищется.

Значит сначала я неверно понял исходную проблему:

> запись не находиться по uuid, и далее происходит обращение к несуществующему объекту

Но сейчас представляется, что в файлах индексов мантикоры отсутствуют или перемещены какие-то поля для ряда записей в результате неустановленной проблемы. 

> если уж так прямо заморочится, то можно написать программу, взять каждую текстовую запись из БД, например одно предложение и отправить в поиск, получить результат, если не найдено записать запрос в лог для проверки, если ок записать uuid записи в лог и потом как-то проанализировать

Как-то кажется избыточным, правильно? Насколько мне понятно: раз проблема детектируется при обращении к контексту, и поскольку контекст формируется по uuid, значит существует какой-то алгоритм перебора uuid, который позволит зафиксировать исключение при обращении к нему.

**Comment by audetv** [comment]
Технические работы на lib.svodd.ru загрузка нового индекса.
При переиндексировании документов выявленные параграфы, которые давали ошибки при вызове контекста, стали открываться. 

UPD: выполнено 31.08.2023 15:11 мск

**Comment by iprst** [comment]
Все перечисленные параграфы теперь отдают контекст без ошибки.

**Comment by audetv** [comment]
Закрыл этот issue, будем иметь ввиду, 
Если подобные случаи будут повторяться, будем лечить переиндексацией,
до выявления закономерности , пока не хочу углубляться, почему это произошло.
Понаблюдаю, подумал, что надо повесить оповещение, на открытие контекста с ошибкой, чтобы приходил email, доработаю.

**Comment by iprst** [comment]
Понял. Будем следить. Если было бы понятно про набор возможных причин, можно было бы придумать какой-то локальный тест, наверное, но пока ничего не понятно.
